# Generated by Django 4.2.5 on 2023-09-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('side_app', '0002_alter_phonebool_about_alter_phonebool_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebool',
            name='about',
            field=models.CharField(max_length=150, verbose_name='About'),
        ),
    ]
