# Generated by Django 4.2.5 on 2023-09-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('side', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(default='', max_length=50),
        ),
    ]
