# Generated by Django 4.2.5 on 2023-09-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('permalink', models.CharField(max_length=24, unique=True, verbose_name='Permalink')),
                ('bodytext', models.TextField(blank=True, verbose_name='Bodytext')),
                ('update_date', models.DateTimeField(verbose_name='Update_date')),
            ],
        ),
    ]
