# Generated by Django 4.2.5 on 2023-10-08 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writing', models.TextField(verbose_name='writing')),
                ('type', models.CharField(max_length=10, verbose_name='type')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witer', to='rest_api.author')),
            ],
        ),
    ]
