# Generated by Django 4.2.5 on 2023-10-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=300)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField()),
                ('responsible', models.CharField(max_length=200)),
            ],
        ),
    ]
